### ISSUE TITLE
Can you add documentation and other annotations?

### ISSUE THREAD

**Issue by rattrayalex** [lightsofapollo/joi-to-json-schema#63]
Is it possible to do something like this?

```
foo: joi.string().meta({title: "Foo", description: "This is a foo", "x-myattribute": true})

// convert into:
foo: 
  type: 'string'
  title: 'Foo' 
  description: 'This is a foo'
  x-myattribute: true
```

I want to use title, description, and custom annotations for openapi via [joi-to-openapi-definition](https://www.npmjs.com/package/joi-to-openapi-definition).
